### ISSUE TITLE
Small error in README, number of bits for p is 16

### ISSUE THREAD

**Issue by wyssli** [wg/scrypt#18]
>   params - 32-bit hex integer containing log2(N) (16 bits), r (8 bits), and p (8 bits)

should be:

params - 40-bit hex integer containing log2(N) (16 bits), r (8 bits), and p (16 bits)

**Comment by MrBerg** [comment]
Where do you see that it should be 40-bit, @wyssli? https://github.com/wg/scrypt/blob/master/src/main/java/com/lambdaworks/crypto/SCryptUtil.java#L49 seems to hint pretty clearly at p being 8 bits long since r is left-shifted 8 bits.

**Comment by JeffreyLeonard** [comment]
What

**Comment by Wahirapol** [comment]
ในวันที่ ส. 6 ต.ค. 2018 01:32 Jeffrey Leonard <notifications@github.com>
เขียนว่า:

> What
>

**Comment by wyssli** [comment]
you are right, I don't know what I was thinking at the time...
Maybe I was struggling  because i chose a N which was not 2^x, which results in Errors...
ANyway, I'm closing this mea culpa etc. etc.
