### ISSUE TITLE
Weird Maven artifacts

### ISSUE THREAD

**Issue by yang** [wg/scrypt#2]
When downloading the maven jar, it seems to consist of three sub-jars: 

```
$ jar tf ~/.ivy2/cache/com.lambdaworks/scrypt/jars/scrypt-1.1.0.jar
META-INF/
META-INF/MANIFEST.MF
pom.xml
scrypt-1.1.0.jar
scrypt-1.1.0.pom.asc
scrypt-1.1.0-javadoc.jar
scrypt-1.1.0-sources.jar
scrypt-1.1.0-javadoc.jar.asc
scrypt-1.1.0-sources.jar.asc
```

I've never seen jars like this and the tools I'm using (Eclipse, Ivy, sbt, etc.) don't get to use this the right way. Would be great if you could fix this (these sub-jars should be hoisted up out of the parent jar and into the hosted Maven directory). Thanks!

**Comment by wg** [comment]
Thanks yang! Looks like I don't yet fully grok the maven release process.

I wasn't able to replace version 1.1.0 with a fixed bundle, so instead I've released 1.1.1 which is the same version of the code. I've also released 1.2.0 which includes native libraries for x86_64 linux and darwin (Mac OS X).
